schema_version: 1

context:
  name: colour-science
  version: "0.4.7"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/colour_science-${{ version }}.tar.gz
  sha256: b34773dc4dd3f9ba99cca5297fa10e9f532134d994b3a2308dacbe970dfd5079

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
    - hatch
  run:
    - python >=${{ python_min }}
    - imageio >=2,<3
    - matplotlib-base >=3.7
    - numpy >=1.24,<3
    - scipy >=1.10,<2
    - typing_extensions >=4,<5

tests:
  - python:
      imports:
        - colour
        - colour.colorimetry
        - colour.io
        - colour.plotting
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Colour Science for Python
  homepage: https://www.colour-science.org/
  repository: https://github.com/colour-science/colour
  documentation: https://colour.readthedocs.io/

extra:
  recipe-maintainers:
    - thomasmansencal
    - MichaelMauderer
    - carlodri
